SELECT 
    c.CAR_ID,
    c.CAR_TYPE,
    ROUND(30 * c.DAILY_FEE * (1 - d.DISCOUNT_RATE / 100)) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR c
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
    ON c.CAR_TYPE = d.CAR_TYPE AND d.DURATION_TYPE = '30일 이상'
LEFT JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    ON c.CAR_ID = h.CAR_ID
WHERE 
    c.CAR_TYPE IN ('세단', 'SUV')
    AND NOT EXISTS (
        SELECT 1 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h2
        WHERE h2.CAR_ID = c.CAR_ID 
          AND (
            (h2.START_DATE BETWEEN '2022-11-01' AND '2022-11-30') 
            OR (h2.END_DATE BETWEEN '2022-11-01' AND '2022-11-30')
            OR (h2.START_DATE <= '2022-11-01' AND h2.END_DATE >= '2022-11-30')
          )
    )
    AND ROUND(30 * c.DAILY_FEE * (1 - d.DISCOUNT_RATE / 100)) >= 500000
    AND ROUND(30 * c.DAILY_FEE * (1 - d.DISCOUNT_RATE / 100)) < 2000000
GROUP BY 
    c.CAR_ID, c.CAR_TYPE, c.DAILY_FEE, d.DISCOUNT_RATE
ORDER BY 
    FEE DESC, 
    c.CAR_TYPE ASC, 
    c.CAR_ID DESC;