SELECT DATE_FORMAT(S.SALES_DATE, '%Y') AS YEAR, DATE_FORMAT(S.SALES_DATE, '%m') AS MONTH, COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT U.USER_ID) / (SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE JOINED LIKE '2021%'), 1) AS PURCHASED_RATIO
FROM USER_INFO AS U
INNER JOIN ONLINE_SALE AS S ON U.USER_ID = S.USER_ID
WHERE DATE_FORMAT(U.JOINED, '%Y') = '2021'
GROUP BY DATE_FORMAT(S.SALES_DATE, '%Y'), DATE_FORMAT(S.SALES_DATE, '%m')
ORDER BY DATE_FORMAT(S.SALES_DATE, '%Y') ASC, DATE_FORMAT(S.SALES_DATE, '%m') ASC;